# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: vss-report-s3
  namespace: <NAMESPACE>
spec:
  selector:
    app: vss-report-s3
  ports:
    - name: s3
      port: 8333
      targetPort: s3
